// <auto-generated />
using System;
using System.Collections.Generic;
using DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829181146_CascadeDeleteForRoutesTransactions")]
    partial class CascadeDeleteForRoutesTransactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Classes.MapCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CellId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<int>("SchemaId")
                        .HasColumnType("integer");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SourceStationId")
                        .HasColumnType("integer");

                    b.Property<int?>("StationId")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetStationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SchemaId");

                    b.HasIndex("SourceStationId");

                    b.HasIndex("StationId");

                    b.HasIndex("TargetStationId");

                    b.ToTable("MapCells");

                    b.HasAnnotation("Relational:JsonPropertyName", "cells");
                });

            modelBuilder.Entity("Domain.Classes.MapSchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MapSchemas");
                });

            modelBuilder.Entity("Domain.Classes.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("RouteNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RowInFile")
                        .HasColumnType("integer");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Domain.Classes.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("TransactionId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Domain.Classes.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayInRaise")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Distance")
                        .HasColumnType("integer");

                    b.Property<bool>("HasDesc")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RailcarCount")
                        .HasColumnType("integer");

                    b.Property<int>("RangePerDay")
                        .HasColumnType("integer");

                    b.Property<int>("RangePerMonth")
                        .HasColumnType("integer");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.Property<int>("RowInFile")
                        .HasColumnType("integer");

                    b.Property<int>("StationFromId")
                        .HasColumnType("integer");

                    b.Property<int?>("StationMiddleId")
                        .HasColumnType("integer");

                    b.Property<int>("StationToId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("TimeFrom")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("TimeTo")
                        .HasColumnType("time without time zone");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.Property<int>("month")
                        .HasColumnType("integer");

                    b.Property<int>("year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("StationFromId");

                    b.HasIndex("StationMiddleId");

                    b.HasIndex("StationToId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("Domain.Classes.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UnitsGet")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Domain.Classes.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Classes.WayRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("StationFromId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<int>>("StationIdsInWay")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int?>("StationMiddleId")
                        .HasColumnType("integer");

                    b.Property<int>("StationToId")
                        .HasColumnType("integer");

                    b.Property<int>("wayLength")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StationFromId");

                    b.HasIndex("StationMiddleId");

                    b.HasIndex("StationToId");

                    b.ToTable("WayRecords");
                });

            modelBuilder.Entity("Domain.Classes.MapCell", b =>
                {
                    b.HasOne("Domain.Classes.MapSchema", "Schema")
                        .WithMany("MapCells")
                        .HasForeignKey("SchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Classes.Station", "SourceStation")
                        .WithMany()
                        .HasForeignKey("SourceStationId");

                    b.HasOne("Domain.Classes.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId");

                    b.HasOne("Domain.Classes.Station", "TargetStation")
                        .WithMany()
                        .HasForeignKey("TargetStationId");

                    b.OwnsOne("Domain.Classes.Coords", "Position", b1 =>
                        {
                            b1.Property<int>("MapCellId")
                                .HasColumnType("integer");

                            b1.Property<int>("X")
                                .HasColumnType("integer")
                                .HasColumnName("x");

                            b1.Property<int>("Y")
                                .HasColumnType("integer")
                                .HasColumnName("y");

                            b1.HasKey("MapCellId");

                            b1.ToTable("MapCells");

                            b1.WithOwner()
                                .HasForeignKey("MapCellId");
                        });

                    b.OwnsOne("Domain.Classes.Data", "Data", b1 =>
                        {
                            b1.Property<int>("MapCellId")
                                .HasColumnType("integer");

                            b1.Property<string>("Label")
                                .HasColumnType("text")
                                .HasColumnName("Label");

                            b1.Property<int?>("Load")
                                .HasColumnType("integer")
                                .HasColumnName("Load");

                            b1.HasKey("MapCellId");

                            b1.ToTable("MapCells");

                            b1.WithOwner()
                                .HasForeignKey("MapCellId");
                        });

                    b.OwnsOne("Domain.Classes.CellReference", "Source", b1 =>
                        {
                            b1.Property<int>("MapCellId")
                                .HasColumnType("integer");

                            b1.Property<string>("Cell")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Source");

                            b1.Property<string>("Port")
                                .HasColumnType("text")
                                .HasColumnName("SourcePort");

                            b1.HasKey("MapCellId");

                            b1.ToTable("MapCells");

                            b1.WithOwner()
                                .HasForeignKey("MapCellId");
                        });

                    b.OwnsOne("Domain.Classes.CellReference", "Target", b1 =>
                        {
                            b1.Property<int>("MapCellId")
                                .HasColumnType("integer");

                            b1.Property<string>("Cell")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Target");

                            b1.Property<string>("Port")
                                .HasColumnType("text")
                                .HasColumnName("TargetPort");

                            b1.HasKey("MapCellId");

                            b1.ToTable("MapCells");

                            b1.WithOwner()
                                .HasForeignKey("MapCellId");
                        });

                    b.Navigation("Data")
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Schema");

                    b.Navigation("Source");

                    b.Navigation("SourceStation");

                    b.Navigation("Station");

                    b.Navigation("Target");

                    b.Navigation("TargetStation");
                });

            modelBuilder.Entity("Domain.Classes.Route", b =>
                {
                    b.HasOne("Domain.Classes.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Classes.PasCategory", "Another", b1 =>
                        {
                            b1.Property<int>("RouteId")
                                .HasColumnType("integer");

                            b1.Property<int>("Count")
                                .HasColumnType("integer")
                                .HasColumnName("Another_Count");

                            b1.Property<double>("Payment")
                                .HasColumnType("double precision")
                                .HasColumnName("Another_Payment");

                            b1.Property<double>("PaymentBySubject")
                                .HasColumnType("double precision")
                                .HasColumnName("Another_PaymentBySubject");

                            b1.Property<double>("WayLength")
                                .HasColumnType("double precision")
                                .HasColumnName("Another_WayLength");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.OwnsOne("Domain.Classes.PasCategory", "Casual", b1 =>
                        {
                            b1.Property<int>("RouteId")
                                .HasColumnType("integer");

                            b1.Property<int>("Count")
                                .HasColumnType("integer")
                                .HasColumnName("Casual_Count");

                            b1.Property<double>("Payment")
                                .HasColumnType("double precision")
                                .HasColumnName("Casual_Payment");

                            b1.Property<double>("PaymentBySubject")
                                .HasColumnType("double precision")
                                .HasColumnName("Casual_PaymentBySubject");

                            b1.Property<double>("WayLength")
                                .HasColumnType("double precision")
                                .HasColumnName("Casual_WayLength");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.OwnsOne("Domain.Classes.PasCategory", "FedBenefit", b1 =>
                        {
                            b1.Property<int>("RouteId")
                                .HasColumnType("integer");

                            b1.Property<int>("Count")
                                .HasColumnType("integer")
                                .HasColumnName("FedBenefit_Count");

                            b1.Property<double>("Payment")
                                .HasColumnType("double precision")
                                .HasColumnName("FedBenefit_Payment");

                            b1.Property<double>("PaymentBySubject")
                                .HasColumnType("double precision")
                                .HasColumnName("FedBenefit_PaymentBySubject");

                            b1.Property<double>("WayLength")
                                .HasColumnType("double precision")
                                .HasColumnName("FedBenefit_WayLength");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.OwnsOne("Domain.Classes.PasCategory", "RegBenefit", b1 =>
                        {
                            b1.Property<int>("RouteId")
                                .HasColumnType("integer");

                            b1.Property<int>("Count")
                                .HasColumnType("integer")
                                .HasColumnName("RegBenefit_Count");

                            b1.Property<double>("Payment")
                                .HasColumnType("double precision")
                                .HasColumnName("RegBenefit_Payment");

                            b1.Property<double>("PaymentBySubject")
                                .HasColumnType("double precision")
                                .HasColumnName("RegBenefit_PaymentBySubject");

                            b1.Property<double>("WayLength")
                                .HasColumnType("double precision")
                                .HasColumnName("RegBenefit_WayLength");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.OwnsOne("Domain.Classes.PasCategory", "Student", b1 =>
                        {
                            b1.Property<int>("RouteId")
                                .HasColumnType("integer");

                            b1.Property<int>("Count")
                                .HasColumnType("integer")
                                .HasColumnName("Student_Count");

                            b1.Property<double>("Payment")
                                .HasColumnType("double precision")
                                .HasColumnName("Student_Payment");

                            b1.Property<double>("PaymentBySubject")
                                .HasColumnType("double precision")
                                .HasColumnName("Student_PaymentBySubject");

                            b1.Property<double>("WayLength")
                                .HasColumnType("double precision")
                                .HasColumnName("Student_WayLength");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.Navigation("Another")
                        .IsRequired();

                    b.Navigation("Casual")
                        .IsRequired();

                    b.Navigation("FedBenefit")
                        .IsRequired();

                    b.Navigation("RegBenefit")
                        .IsRequired();

                    b.Navigation("Student")
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Domain.Classes.Station", b =>
                {
                    b.HasOne("Domain.Classes.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Domain.Classes.Train", b =>
                {
                    b.HasOne("Domain.Classes.Route", "Route")
                        .WithMany("Trains")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Classes.Station", "StationFrom")
                        .WithMany()
                        .HasForeignKey("StationFromId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Classes.Station", "StationMiddle")
                        .WithMany()
                        .HasForeignKey("StationMiddleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Classes.Station", "StationTo")
                        .WithMany()
                        .HasForeignKey("StationToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Classes.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("StationFrom");

                    b.Navigation("StationMiddle");

                    b.Navigation("StationTo");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Domain.Classes.Transaction", b =>
                {
                    b.HasOne("Domain.Classes.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Classes.WayRecord", b =>
                {
                    b.HasOne("Domain.Classes.Station", "StationFrom")
                        .WithMany()
                        .HasForeignKey("StationFromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Classes.Station", "StationMiddle")
                        .WithMany()
                        .HasForeignKey("StationMiddleId");

                    b.HasOne("Domain.Classes.Station", "StationTo")
                        .WithMany()
                        .HasForeignKey("StationToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StationFrom");

                    b.Navigation("StationMiddle");

                    b.Navigation("StationTo");
                });

            modelBuilder.Entity("Domain.Classes.MapSchema", b =>
                {
                    b.Navigation("MapCells");
                });

            modelBuilder.Entity("Domain.Classes.Route", b =>
                {
                    b.Navigation("Trains");
                });
#pragma warning restore 612, 618
        }
    }
}
