// <auto-generated />
using System;
using DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260801203800_AddTransactionClass")]
    partial class AddTransactionClass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Classes.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("RouteNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Domain.Classes.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Domain.Classes.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayInRaise")
                        .HasColumnType("integer");

                    b.Property<int>("Distance")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RailcarCount")
                        .HasColumnType("integer");

                    b.Property<int>("RangePerDay")
                        .HasColumnType("integer");

                    b.Property<int>("RangePerMonth")
                        .HasColumnType("integer");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.Property<int>("StationFromId")
                        .HasColumnType("integer");

                    b.Property<int?>("StationMiddleId")
                        .HasColumnType("integer");

                    b.Property<int>("StationToId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("TimeFrom")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("TimeTo")
                        .HasColumnType("time without time zone");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("StationFromId");

                    b.HasIndex("StationMiddleId");

                    b.HasIndex("StationToId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("Domain.Classes.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.Property<int>("UnitsGet")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Domain.Classes.Route", b =>
                {
                    b.HasOne("Domain.Classes.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Classes.PasCategory", "Another", b1 =>
                        {
                            b1.Property<int>("RouteId")
                                .HasColumnType("integer");

                            b1.Property<int>("Count")
                                .HasColumnType("integer")
                                .HasColumnName("Another_Count");

                            b1.Property<double>("Payment")
                                .HasColumnType("double precision")
                                .HasColumnName("Another_Payment");

                            b1.Property<double>("PaymentBySubject")
                                .HasColumnType("double precision")
                                .HasColumnName("Another_PaymentBySubject");

                            b1.Property<double>("WayLength")
                                .HasColumnType("double precision")
                                .HasColumnName("Another_WayLength");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.OwnsOne("Domain.Classes.PasCategory", "Casual", b1 =>
                        {
                            b1.Property<int>("RouteId")
                                .HasColumnType("integer");

                            b1.Property<int>("Count")
                                .HasColumnType("integer")
                                .HasColumnName("Casual_Count");

                            b1.Property<double>("Payment")
                                .HasColumnType("double precision")
                                .HasColumnName("Casual_Payment");

                            b1.Property<double>("PaymentBySubject")
                                .HasColumnType("double precision")
                                .HasColumnName("Casual_PaymentBySubject");

                            b1.Property<double>("WayLength")
                                .HasColumnType("double precision")
                                .HasColumnName("Casual_WayLength");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.OwnsOne("Domain.Classes.PasCategory", "FedBenefit", b1 =>
                        {
                            b1.Property<int>("RouteId")
                                .HasColumnType("integer");

                            b1.Property<int>("Count")
                                .HasColumnType("integer")
                                .HasColumnName("FedBenefit_Count");

                            b1.Property<double>("Payment")
                                .HasColumnType("double precision")
                                .HasColumnName("FedBenefit_Payment");

                            b1.Property<double>("PaymentBySubject")
                                .HasColumnType("double precision")
                                .HasColumnName("FedBenefit_PaymentBySubject");

                            b1.Property<double>("WayLength")
                                .HasColumnType("double precision")
                                .HasColumnName("FedBenefit_WayLength");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.OwnsOne("Domain.Classes.PasCategory", "RegBenefit", b1 =>
                        {
                            b1.Property<int>("RouteId")
                                .HasColumnType("integer");

                            b1.Property<int>("Count")
                                .HasColumnType("integer")
                                .HasColumnName("RegBenefit_Count");

                            b1.Property<double>("Payment")
                                .HasColumnType("double precision")
                                .HasColumnName("RegBenefit_Payment");

                            b1.Property<double>("PaymentBySubject")
                                .HasColumnType("double precision")
                                .HasColumnName("RegBenefit_PaymentBySubject");

                            b1.Property<double>("WayLength")
                                .HasColumnType("double precision")
                                .HasColumnName("RegBenefit_WayLength");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.OwnsOne("Domain.Classes.PasCategory", "Student", b1 =>
                        {
                            b1.Property<int>("RouteId")
                                .HasColumnType("integer");

                            b1.Property<int>("Count")
                                .HasColumnType("integer")
                                .HasColumnName("Student_Count");

                            b1.Property<double>("Payment")
                                .HasColumnType("double precision")
                                .HasColumnName("Student_Payment");

                            b1.Property<double>("PaymentBySubject")
                                .HasColumnType("double precision")
                                .HasColumnName("Student_PaymentBySubject");

                            b1.Property<double>("WayLength")
                                .HasColumnType("double precision")
                                .HasColumnName("Student_WayLength");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.Navigation("Another")
                        .IsRequired();

                    b.Navigation("Casual")
                        .IsRequired();

                    b.Navigation("FedBenefit")
                        .IsRequired();

                    b.Navigation("RegBenefit")
                        .IsRequired();

                    b.Navigation("Student")
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Domain.Classes.Station", b =>
                {
                    b.HasOne("Domain.Classes.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Domain.Classes.Train", b =>
                {
                    b.HasOne("Domain.Classes.Route", "Route")
                        .WithMany("Trains")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Classes.Station", "StationFrom")
                        .WithMany()
                        .HasForeignKey("StationFromId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Classes.Station", "StationMiddle")
                        .WithMany()
                        .HasForeignKey("StationMiddleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Classes.Station", "StationTo")
                        .WithMany()
                        .HasForeignKey("StationToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Classes.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("StationFrom");

                    b.Navigation("StationMiddle");

                    b.Navigation("StationTo");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Domain.Classes.Route", b =>
                {
                    b.Navigation("Trains");
                });
#pragma warning restore 612, 618
        }
    }
}
